### ISSUE TITLE
Could not find package laracasts/behat-laravel-extension

### ISSUE THREAD

**Issue by zmorris** [laracasts/Behat-Laravel-Extension#10]
I ran the command according to the readme but it couldn't find behat-laravel-extension.  I am new to Laravel so this could easily be a problem existing between keyboard and chair.  Mac OS 10.10.1 Yosemite, php 5.5.14.

`composer require behat/behat behat/mink behat/mink-extension laracasts/behat-laravel-extension --dev`

```
Using version ~3.0 for behat/behat
Using version ~1.6 for behat/mink
Using version ~2.0 for behat/mink-extension



  [InvalidArgumentException]                                                                                                                           
  Could not find package laracasts/behat-laravel-extension at any version for your minimum-stability (stable). Check the package spelling or your min  
  imum-stability                                                                                                                                       



require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]
```

**Comment by zmorris** [comment]
Ok updating the composer.json at the root level of my project from:

```
"preferred-install": "stable"
```

to:

```
"preferred-install": "dev"
```

Fixed it.  I don't know if leaving the composer.json files at these other locations as "stable" will hurt anything:

```
vendor/laravel/framework/src/Illuminate/Workbench/stubs/composer.json
vendor/laravel/framework/src/Illuminate/Workbench/stubs/plain.composer.json
```

My original setup command was:

```
composer create-project laravel/laravel your-project-name --prefer-dist
```

**Comment by RomainLanz** [comment]
@JeffreyWay Do you know when you are going to change that?

**Comment by ehkasper** [comment]
+1

**Comment by fntneves** [comment]
Same here...

**Comment by jonlambert** [comment]
Yep me too!

**Comment by abbajbryant** [comment]
Seems for now you can add it to your composer.json manually - the stability requirements seem to have changed.

in composer.json: "laracasts/behat-laravel-extension": "dev-master"

**Comment by marcusmoore** [comment]
@zmorris I THINK it would be best to keep `"preferred-install": "stable"` in your composer file and then require `dev-master` for this package specifically.

**Comment by fer-ri** [comment]
I think its all because you run composer require vendor/package without define any version, so default composer will try to look stable version ..

**Comment by rossedman** [comment]
@marcusmoore88 :+1: I agree

**Comment by coquer** [comment]
+1

**Comment by alnutile** [comment]
going to close this feel free to reopen if needed.
