### ISSUE TITLE
Modifying authenticated user and persistence of the flash messages

### ISSUE THREAD

**Issue by tmalecki** [laracasts/Behat-Laravel-Extension#12]
While working with Behat and the Laravel Extension I have encountered the following issues:
1. After we modify the authenticated user the changes are not visible until the user relogs. That’s probably due to requests, which are made using the same instance of the application. If the user is signed in, it's stored in the memory to the end of a scenario.
   
   https://github.com/laravel/framework/blob/5.0/src/Illuminate/Auth/Guard.php#L134-L137
2. The flash messages are persistent. They should disappear after page’s reload but that doesn’t happen.

I have created a repository with exemplary tests, which show above mentioned issues.

https://github.com/tmalecki/l5-behat-test

Thanks.

**Comment by bcat-eu** [comment]
+1, at the moment Mink reload() Method is a little confusing because of that (flash messages, filled in form fields etc). As a workaround a "true" reload can be implemented in a context class or a trait like this:

```
/**
 * Reload page and delete session data.
 *
 * @When I reload page and flush session
 */
public function reloadAndFlush()
{
    Session::flush();
    $this->reload();

}
```

**Comment by alnutile** [comment]
@bcat-eu thanks!

going to close this feel free to reopen if needed.
