### ISSUE TITLE
Installation issue with official release of Laravel 5

### ISSUE THREAD

**Issue by haoyuguo** [laracasts/Behat-Laravel-Extension#16]
I got the following issue while installing laracasts/behat-laravel-extension with the newly released Laravel 5.

I was trying to follow this laracast:

https://laracasts.com/lessons/laravel-5-and-behat-bffs

And I got the some prophecy version error.

I was able to install behat/behat, behat/mink, behat/mink-extension first, but when trying laracasts/behat-laravel-extension after that, the same errors showed up again. Error messages are at the bottom of this comment.

I wonder if there's a simple answer to that. If not, I'd love to explore a solution by myself, if someone could kindly give me a pointer to start with.

Thanks!

H. Guo
# 

php composer.phar require laracasts/behat-laravel-extension

Using version dev-master for laracasts/behat-laravel-extension./composer.json has been updated
Loading composer repositories with package information Updating dependencies (including require-dev)

[RuntimeException]

Could not load package phpspec/prophecy in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.0.2: Invalid version string "^1.0.2"

[UnexpectedValueException]
Could not parse version constraint ^1.0.2: Invalid version string "^1.0.2"

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [packages1] ... [packagesN]

**Comment by RomainLanz** [comment]
Update your composer's version.

```
php composer.phar selfupdate
```

**Comment by alnutile** [comment]
@haoyuguo going to close this feel free to reopen if needed.
