### ISSUE TITLE
Use with Laravel 4

### ISSUE THREAD

**Issue by rmarliere** [laracasts/Behat-Laravel-Extension#17]
Can I use this with Laravel 4?
I'm getting the error [RuntimeException] Could not locate the path to the Laravel bootstrap file.

Is there any way to solve this?

**Comment by laracasts** [comment]
This extension is for Laravel 5.

**Comment by cve** [comment]
Is there any similar extension for L4? We have a huge project based on L4, and we want to switch to L5 in the future, but now we want to use Behat with L4, any guidelines for that use case?
