### ISSUE TITLE
Mink base_url param causes fail

### ISSUE THREAD

**Issue by jazerix** [laracasts/Behat-Laravel-Extension#22]
When using the base_url param in the behat.yml file, every scenario after the first one fails. This is caused because the laracasts extension isn't rebooting with the baseUrl, like it is when it starts up the first time.

https://github.com/Behat/MinkExtension/issues/196

I tried fixing it myself, with no luck :disappointed:

**Comment by alnutile** [comment]
I will look in a bit but in the mean time if you set your constructor as such

```
    public function __construct()
    {
        $this->baseUrl = env('APP_URL');
    }
```

And set that as needed in the .env file. 

Kludgy but it works well. 

But I will see about doing it in the extension.

**Comment by alnutile** [comment]
going to close this feel free to reopen if needed.
