### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by MRezaNasirloo** [laracasts/Behat-Laravel-Extension#28]
Hi,
Is it possible to use dependency injection in Context classes?
Phpstorm's behat integration can't find facades and complaints about them.
I have used constructor parameters with **behat.yml** file but looks like it just works with plains strings.

**Comment by rossedman** [comment]
@Pedramrn to have PHPStorm recognize and help you with classes you can use [Laravel IDE Helper](https://github.com/barryvdh/laravel-ide-helper). I don't know if that solves your problem. I know PHPStorm has recognized parameters for me.

**Comment by alnutile** [comment]
@Pedramrn did you figure this out?

Do You mean just in the constructor of the context?  Issue #2 might talk about this a bit. Some I just use App::make to instatiane the class for me when i need it.

**Comment by MRezaNasirloo** [comment]
@alnutile That was a long time ago, Sorry I don't remember.

**Comment by alnutile** [comment]
:)

**Comment by alnutile** [comment]
Feel free to open again if needed
