### ISSUE TITLE
Model events are only triggered once

### ISSUE THREAD

**Issue by bcat-eu** [laracasts/Behat-Laravel-Extension#31]
If I have a feature with a single scenario that triggers model events (saving) everything is good.

If I run this feature with other tests or have few scenarios in the same feature - only the first one triggers the model event, rest are ignored.

Example (always works if only this feature file is called):

```
Scenario: paid invoice does have enough payments
    Given I have a "paid" invoice
    When I remove payments so that the total is not covered
    Then invoices totals should match isPaid field value   
```

Example 2 (first scenario works, second does not):

```
Scenario: unpaid invoice does not have enough payments
   Given I have an "unpaid" invoice
   When I add payments so that the total is covered
   Then invoices totals should match isPaid field value

Scenario: paid invoice does have enough payments
   Given I have a "paid" invoice
   When I remove payments so that the total is not covered
   Then invoices totals should match isPaid field value   
```

Example 3 (same as 2 but switched - still first works, second does not):

```
Scenario: paid invoice does have enough payments
   Given I have a "paid" invoice
   When I remove payments so that the total is not covered
   Then invoices totals should match isPaid field value   

Scenario: unpaid invoice does not have enough payments
   Given I have an "unpaid" invoice
   When I add payments so that the total is covered
   Then invoices totals should match isPaid field value
```

**Comment by sakalys** [comment]
Had a similar issue. My problem was that I had multiple model files for the same resource. All of those files extended the BaseMyResourceModel class. I thought that `BaseMyResourceModel::created()` would trigger for all of the descendant models would inherit that event handler. But that is not the case. I had to pick out all the models...

```
MyResourceModel::created(...)
SameResourceInADifferentModule::created(...)
```

**Comment by bcat-eu** [comment]
Not my case, I have simple Models, might have something to do with the way Events are triggered (I use separate Observer class)

Model file:

```
/**
 * Register observer
 */    
public static function boot()
{
    parent::boot();

    self::observe(new ModelObserver);
}
```

and then in ModelObserver.php 

```
/**
 * Update on every change
 */
public function saved($model) {
    ...
}
```

**Comment by alnutile** [comment]
@bcat-eu did you find a solution to this? If not I will look into it.

**Comment by bcat-eu** [comment]
@alnutile it started working after update to Laravel 5.2, I think the project had 5.0 at the time of the issue so it was resolved somewhere in between without much change on the behat extension's side. You can have a look if it works with older Laravel versions though

**Comment by alnutile** [comment]
going to close this feel free to reopen if needed. 

Not sure unless someone brings it up agains if it is worth me trying it in 5.0

I soon will tests running for each version 5.1 and higher
