### ISSUE TITLE
Mailtrap trait error with Guzzle 6

### ISSUE THREAD

**Issue by shaneferguson** [laracasts/Behat-Laravel-Extension#33]
For the past hour or so Ive been wrestling with why my previously working tests were all of a sudden failing. I hadn't realised that during a previous composer update Guzzle had upgrade to version 6. Using 6 i get the following error when trying to use the Mailtrap trait...

cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\RequestException)

Downgrading to Guzzle 5 meant this worked correctly. Not sure what the root cause is here, but it was a painful bug to figure out (for me anyway) so want to alert anyone who may run into the same issue. Might be worth looking into fixing or requiring version 5?

Keep up the good work Jeffrey :)

**Comment by jakubhomoly** [comment]
Fixed in my pull request below

**Comment by gregjkal** [comment]
Thanks @shaneferguson. Was having this problem as well. Glad you shared the workaround, and hope Jeffrey has time to look into this :)

**Comment by alnutile** [comment]
going to close this feel free to reopen if needed.

**Comment by g0ld3lux** [comment]
I tried to implement this fix , but i get this...
error 

```
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\RequestException)
```

**Comment by g0ld3lux** [comment]
Finally i fixed this error , has nothing to do with the fix but with my version of php7
the fix is this

```
http://stackoverflow.com/questions/21114371/php-curl-error-code-60/21114601#21114601
```

**Comment by alnutile** [comment]
wow seems odd. I wonder if setting curl not to verify the cert would help.
