### ISSUE TITLE
Laravel 5.1.4 + Behat + Mailtrap:  getting GuzzleHttp\Exception\RequestException

### ISSUE THREAD

**Issue by fabioi** [laracasts/Behat-Laravel-Extension#37]
I am getting  "cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\RequestException)"  but It seems to me that everything is configured properly. 

Using:
Laravel 5.1.4
 "guzzlehttp/guzzle": "~5.3|~6.0",
"behat/behat": "^3.0",
 "laracasts/behat-laravel-extension": "^1.0"

**Comment by arthurkirkosa** [comment]
Guzzle 5 fixes the issue

**Comment by alnutile** [comment]
going to close this feel free to reopen if needed.
