### ISSUE TITLE
Composer: cannot install Laravel-Behat-Extension on Laravel 5.2

### ISSUE THREAD

**Issue by hbea2014** [laracasts/Behat-Laravel-Extension#41]
I'm following [the tutorial about Behat and BDD](https://laracasts.com/lessons/laravel-5-and-behat-bffs) but I ran into problems with behat, mink and mink-extension.

Creating the new project with (`composer create-project laravel/laravel behat-learning`) worked for me.

Then I ran into errors with behat, mink and mink-extension and the only solution I found was to use their dev-master branches (`composer require behat/behat:dev-master behat/mink:dev-master behat/mink-extension:dev-master --dev`). It worked and as I don't mind using those branches, everything good on my side.

But when I try to install behat-laravel-extension then I got this problem and I am stuck:

Your requirements could not be resolved to an installable set of packages.

```
Problem 1
  - Installation request for laracasts/behat-laravel-extension ^1.0 -> satisfiable by laracasts/behat-laravel-extension[1.0].
  - Conclusion: remove symfony/dom-crawler v3.0.1
  - Conclusion: don't install symfony/dom-crawler v3.0.1
  - laracasts/behat-laravel-extension 1.0 requires behat/mink-browserkit-driver ~1.2 -> satisfiable by behat/mink-browserkit-driver[v1.2.0, v1.3.0].
  - behat/mink-browserkit-driver v1.2.0 requires symfony/dom-crawler ~2.0 -> satisfiable by symfony/dom-crawler[v2.8.0, v2.8.1].
  - behat/mink-browserkit-driver v1.3.0 requires symfony/dom-crawler ~2.3 -> satisfiable by symfony/dom-crawler[v2.8.0, v2.8.1].
  - Can only install one of: symfony/dom-crawler[v2.8.0, v3.0.1].
  - Can only install one of: symfony/dom-crawler[v2.8.1, v3.0.1].
  - Installation request for symfony/dom-crawler == 3.0.1.0 -> satisfiable by symfony/dom-crawler[v3.0.1].
```

It looks like it's about the package itself that's why I'm asking here.

**Comment by gandra** [comment]
I have the same problem.

**Comment by ikari7789** [comment]
`behat/mink-browserkit-driver` will either need to have a new tag created that supports newer symfony components, or the hard dependency for `behat/mink-browserkit-driver` will need to be made optional in this package.

I've made a temporary fix in my own repository that you're welcome to try and use. If you add the following to your composer.json, it should fix the problem. The tags are made using the master branch.

```
"require-dev": {
    "laracasts/behat-laravel-extension": "~1.1"
},
"repositories": [
    {
        "type": "vcs",
        "url": "https://www.github.com/ikari7789/behat-laravel-extension.git"
    },
    {
        "type": "vcs",
        "url": "https://www.github.com/ikari7789/minkbrowserkitdriver.git"
    }
],
```

**Comment by gandra** [comment]
@ikari7789,
your fix works for me. Thanks!

p.s.
If anybody has a issue with  API rate limit check this:
http://tutorials.scrisoft.com/solved-enter-your-github-credentials-to-go-over-the-api-rate-limit/

**Comment by ikari7789** [comment]
This no longer seems to be an issue with the latest release of the mink browser kit driver.
https://github.com/minkphp/MinkBrowserKitDriver/tree/v1.3.2

**Comment by alnutile** [comment]
going to close this feel free to reopen if needed.
