### ISSUE TITLE
Set "show_cmd" parameter in behat.yml ... basic setup does not work

### ISSUE THREAD

**Issue by bizmate** [laracasts/Behat-Laravel-Extension#42]
Hi all

I am currently stuck while running behat with laravel. The error is happening on ->visit function.

Mink maybe does not get some default option to be able to open the page without a custom driver. These set up always used to work and I am wondering what configuration to use since I would like to use a built in way just like laravel extension promises, without selenium goutte etc.

When i run behat i get

```
Feature: Laravel 5 page
  As a behat tester
  In order use behat mink correctly
  I want to see the homepage to make sure visit does not throw a show_cmd exception

  Scenario: Laravel startup page displaying correctly # features/example.feature:6
    Given I am on the homepage                        # FeatureContext::iAmOnHomepage()
    Then show last response                           # FeatureContext::showLastResponse()
      Set "show_cmd" parameter in behat.yml to be able to open page in browser (ex.: "show_cmd: firefox %s") (RuntimeException)
    Then I should see "Laravel 5"                     # FeatureContext::assertPageContainsText()

--- Failed scenarios:

    features/example.feature:6

1 scenario (1 failed)
3 steps (1 passed, 1 failed, 1 skipped)
```

I have created a repo with a docker-compose setup and instructions on how to reproduce in details at https://github.com/bizmate/behat_show_cmd

Also i have tested without goutte: ~ but i still need the show_cmd or it will not work

for instance with 

```
Behat\MinkExtension:
      default_session: laravel
      laravel: ~
```

Am I missing anything? If you are on linux u can run it fast and check with `docker-compose up`

**Comment by karlomikus** [comment]
If you want to use showLastResponse method you need to setup browser emulation (ex. selenium), otherwise you can use printLastResponse method which outputs response in console.

**Comment by alnutile** [comment]
@bizmate did you solve this? Honestly I think it is in your behat.yml settings.  Here is are two working behat.yml examples

https://github.com/alnutile/codeship-behat/blob/master/behat.yml

https://github.com/alnutile/recipes/blob/master/behat.yml

**Comment by alnutile** [comment]
@karlomikus hey just noticed your follow up here too thanks!

**Comment by alnutile** [comment]
Closing for now feel free to open again of needed
