### ISSUE TITLE
Mink instance has not been set on Mink context class. Have you enabled the Mink Extension?

### ISSUE THREAD

**Issue by zagorkakomljanovic** [laracasts/Behat-Laravel-Extension#44]
**Please help!!!**
I want to use **Behat with Laravel** and I have been following these steps here 
https://semaphoreci.com/community/tutorials/getting-started-with-bdd-in-laravel
but in my own laravel project not the default "Laravel 5".

When I run 

> $ behat

I get **error** :

```
Feature:
  In order to prove that Behat works as intended
  We want to test the home page for a phrase
  Scenario: Root Test           # features/hometest.feature:5
    When I am on the homepage   # FeatureContext::iAmOnHomepage()
```
## Mink instance has not been set on Mink context class. Have you enabled the Mink Extension? (RuntimeException)

```
    Then I should see "Welcome" # FeatureContext::assertPageContainsText()
--- Failed scenarios:
    features/hometest.feature:5
1 scenario (1 failed)
2 steps (1 failed, 1 skipped)
0m0.04s (11.91Mb)
```

**Commands** that I user in root directory of my Laravel project are :

> ```
> composer require behat/behat behat/mink behat/mink-extension laracasts/behat-laravel-extension --dev
> sudo ln -s /home/vagrant/Code/bdd-setup/vendor/bin/behat /usr/local/bin/behat
> 
> behat --init
> ```

 I have added extensions in my FeatureContext.php 

> class FeatureContext extends _Behat\MinkExtension\Context\MinkContext_
> implements Context, SnippetAcceptingContext
> 
>    cp .env .env.behat0
> 
> ```
> php -S localhost:8888 -t public
> 
> behat
> ```

Here are my **files**: 

```
<?php

use Behat\Behat\Context\Context;
use Behat\Behat\Context\SnippetAcceptingContext;
use Behat\Gherkin\Node\PyStringNode;
use Behat\Gherkin\Node\TableNode;


class FeatureContext extends Behat\MinkExtension\Context\MinkContext implements Context, SnippetAcceptingContext
{

    public function __construct()
    {
    }
}
```

**_env.behat**_

```
APP_ENV=local
APP_KEY=base64:I22b/3uOm+B/H793P8aWQ5CucfiCxoMZ/H3JG6aYoLo=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=sqlite


CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

**_behat.yml**_

```
default:
    extensions:
        Laracasts\Behat:
            # env_path: .env.behat
        Behat\MinkExtension:
            default_session: laravel
            base_url: http://localhost:8888
            laravel: ~
```

And my composer.json requires are :

```
"name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*",
        "behat/behat": "^3.1",
        "behat/mink": "^1.7",
        "behat/mink-extension": "^2.2",
        "laracasts/behat-laravel-extension": "^1.0"
    },
```

**Comment by zairl23** [comment]
@zagorkakomljanovic , i face the same issue, could you tell me how to fix the problem?

**Comment by sshamsudheen** [comment]
I am facing the same problem.. any solution?

**Comment by loichu** [comment]
I ran into this issue and the problem was simply that I put `behat.yml` in the wrong directory. It's quite dumb but as always, make sure that all your files are in the good directory.
