### ISSUE TITLE
Fatal error: Class 'Config' not found (Behat\Testwork\Call\Exception\FatalThrowableError)

### ISSUE THREAD

**Issue by smijo149** [laracasts/Behat-Laravel-Extension#50]
It just doesn't work with Laravel 5.3 :-/

**Comment by alnutile** [comment]
I use it here in 5.3
https://github.com/alnutile/codeship-behat/blob/master/composer.json

See if you can get ideas from that code base.

Also there is an article with it https://github.com/alnutile/codeship-writings/blob/master/behat.md

Maybe it will help

**Comment by alnutile** [comment]
going to close this feel free to reopen if needed.
