### ISSUE TITLE
 cURL error 6: Could not resolve host: http (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\ConnectException)

### ISSUE THREAD

**Issue by g0ld3lux** [laracasts/Behat-Laravel-Extension#56]
I tried Installing it on Laravel 5.3
here is my composer.json file

```
"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "guzzlehttp/guzzle": "^6.2"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "barryvdh/laravel-ide-helper": "^2.2",
        "behat/behat": "^3.1",
        "behat/mink": "^1.7",
        "behat/mink-extension": "^2.2",
        "laracasts/behat-laravel-extension": "^1.0",
        "doctrine/dbal": "^2.5"
    },
```

And Im Just Testing Mail Trap 

```
public function whenTheReportIsDoneTheUserWillGetAnEmailToLetThemKnowItIsDone()
    {
        $lastEmail = $this->fetchInbox()[0];
    }
```

and It Always Throw me this error

```
 cURL error 6: Could not resolve host: http (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\ConnectException)
```

Can Anyone Tag me the Real Fix for this ? So I can just have it merge on my End...
Thanks

**Comment by kscheirer** [comment]
the error is "could not resolve host" - do you have a base_url setting in behat.yml?

**Comment by alnutile** [comment]
darn 17 days @g0ld3lux sorry for the delay.

Did you have all your settings for **mailtrap**?  From the looks of it you might be missing that. If you do not get the error without that `fetchInbox` then I would assume it is related to a setting there.
The docs [https://github.com/laracasts/Behat-Laravel-Extension#service-mailtrap](https://github.com/laracasts/Behat-Laravel-Extension#service-mailtrap)

**Comment by smarques** [comment]
I have the same problem. See
https://github.com/laracasts/Behat-Laravel-Extension/pull/39

This pull request fixes the problem.

**Comment by alnutile** [comment]
I think #51 just fixed this
Reopen if not thanks and sorry for delay
