### ISSUE TITLE
How to use ipv4 in guzzlehttp/guzzle": "^6.2

### ISSUE THREAD

**Issue by ElaheSoleimani** [laracasts/Behat-Laravel-Extension#66]
`exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to -----ipv6-------- Network is unreachable (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

How do I use ipv4 guzzle 6.2?
How is the default for all connections ipv4?

**Comment by alnutile** [comment]
what is the context of the error?

**Comment by ElaheSoleimani** [comment]
exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to -----ipv6-------- Network is unreachable (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by alnutile** [comment]
Yes but when does it happen? How can I recreate it?

**Comment by alnutile** [comment]
What Operating System are you on btw
